### ISSUE TITLE
access denied

### ISSUE THREAD

**Issue by jsteel715** [PBXForums/FusionPBX-API#4]
I generated an API key for a user with superadmin rights but keep getting access denied when attempting a GET request using a browser or postman

**Comment by jsteel715** [comment]
Turned out fail2ban was blocking my ip. Works now

**Comment by ruslanguns** [comment]
I am getting access denied too even disabling fail2ban. How are you sending the url format?

`https://<fusion-pbx>/app/api/contacts/api-key{xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}`

**Comment by jsteel715** [comment]
This format worked for me:  https://<your domain>/app/api/contacts/api-key{<uuid>}
